### ISSUE TITLE
How to run this project ?

### ISSUE THREAD

**Issue by rishabgoyal368** [Anatole-DC/human_behaviour_through_computer_vision#1]
How to run this project, because no python file is uploaded by you. Please check

**Comment by Anatole-DC** [comment]
> How to run this project, because no python file is uploaded by you. Please check

Hi !

This project is a repository for my documentation research in my master, but it's only the beginning of it. For about a year, it will only be filled with documentation results.

Moreover, it will be made in C++ not python, once I'll reach the coding part of this project.

I apologize for the disappointement, I hope that it will be up and running by the end of 2022.
